"""empty message

Revision ID: 0d24702e41a0
Revises: b25f3c885549
Create Date: 2025-06-27 16:30:20.186756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d24702e41a0'
down_revision = 'b25f3c885549'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'deleted_at')
    # ### end Alembic commands ###
